# Experiment Configuration for SDXL DreamBooth with LoHa Adapter

# Base model configuration
pretrained_model_path: "../pretrained_sdxl_model/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b"

# Unique identifier token used during training
unique_token: "zjw"

# Output directories
output_dir: "./outputs_loha" # Specific output directory for LoHa