# Experiment Configuration for SDXL DreamBooth with AdaLora Adapter

# Base model configuration
pretrained_model_path: "stabilityai/stable-diffusion-xl-base-1.0"

# Dataset configuration
dataset_dir: "../dataset"
prompts_file: "../dataset/prompts_and_classes.txt"

# Unique identifier token used during training
unique_token: "zjw"

# Output directories
output_dir: "./outputs_adalora" # Specific output directory for AdaLora

# Mapping of concept names to class names (for evaluation prompts)
# If a concept is not in this mapping, the concept name itself will be used
concept_to_class:
  backpack_dog: "dog with backpack"
  bear_plushie: "teddy bear"
  cat: "cat"
  dog: "dog"
  monster_toy: "monster toy"
  robot_toy: "robot toy"
  teapot: "teapot"
  vase: "vase"
  wolf_plushie: "wolf plushie"

# Evaluation configuration
evaluation:
  num_images_per_prompt: 4
  guidance_scale: 7.5
  num_inference_steps: 25
  seed: 42
  prompt_types:
    - instance_simple
    - instance_detailed
    - class_simple
    - class_detailed

  # Default prompt templates (overridden by prompts_file if provided)
  default_prompt_templates:
    instance_simple: "a photo of [unique_token] [class_name]"
    instance_detailed: "a detailed photo of [unique_token] [class_name], high resolution"
    class_simple: "a photo of [class_name]"
    class_detailed: "a detailed photo of [class_name], high resolution"

  # Additional prompts for creative evaluation
  creative_prompts:
    style_transfer: "a [unique_token] [class_name] in the style of Van Gogh"
    different_context: "a [unique_token] [class_name] in space"
    detailed_scene: "a [unique_token] [class_name] in a beautiful garden, golden hour lighting, high resolution"

# Model paths
pretrained_model_name_or_path: "pretrained_sdxl_model/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b"

# Dataset configuration
instance_data_dir: "dataset/dog"
instance_prompt: "a photo of sks dog"
class_name: "dog"

# Validation settings (can reuse from training_config.yaml if desired)
# validation_prompt: "a photo of sks dog in the snow"
# num_validation_images: 2

# Project organization (can reuse from training_config.yaml if desired)
# log_dir: "sdxl_dreambooth/logs"
# checkpoint_dir: "checkpoints" 