adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.0001
adam_weight_decay_text_encoder: 0.0001
adapter_type: waveft
caption_extension: .txt
center_crop: false
checkpoint_dir: checkpoints
checkpointing_steps: 500
checkpoints_total_limit: 2
class_data_dir: null
class_name: dog
class_prompt: a photo of [class_name]
concept_to_class:
  backpack_dog: dog with backpack
  bear_plushie: teddy bear
  cat: cat
  dog: dog
  monster_toy: monster toy
  robot_toy: robot toy
  teapot: teapot
  vase: vase
  wolf_plushie: wolf plushie
dataloader_num_workers: 0
dataset_dir: ../dataset
enable_xformers_memory_efficient_attention: true
evaluation:
  creative_prompts:
    detailed_scene: a [unique_token] [class_name] in a beautiful garden, golden hour
      lighting, high resolution
    different_context: a [unique_token] [class_name] in space
    style_transfer: a [unique_token] [class_name] in the style of Van Gogh
  default_prompt_templates:
    class_detailed: a detailed photo of [class_name], high resolution
    class_simple: a photo of [class_name]
    instance_detailed: a detailed photo of [unique_token] [class_name], high resolution
    instance_simple: a photo of [unique_token] [class_name]
  guidance_scale: 7.5
  num_images_per_prompt: 4
  num_inference_steps: 25
  prompt_types:
  - instance_simple
  - instance_detailed
  - class_simple
  - class_detailed
  seed: 42
gradient_accumulation_steps: 4
instance_data_dir: ./dataset/dog
instance_prompt: a zjw dog
learning_rate: 0.0001
log_dir: sdxl_dreambooth/logs
logging_steps: 10
lr_num_cycles: 1
lr_power: 1.0
lr_scheduler: constant
lr_warmup_steps: 0
max_grad_norm: 1.0
max_train_steps: 500
measure_memory_usage: false
methods:
- lora
- loha
- lokr
- vera
- fourierft
- adalora
- waveft
mixed_precision: fp16
n_frequency: 2592
num_class_images: 0
num_validation_images: 4
output_dir: /home/abilican21/Peft-League-Clean/./outputs/config/dog
pretrained_model_name_or_path: pretrained_sdxl_model/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b
pretrained_model_path: /home/abilican21/Peft-League/pretrained_sdxl_model/models--stabilityai--stable-diffusion-xl-base-1.0/snapshots/462165984030d82259a11f4367a4eed129e94a7b
prior_loss_weight: 1.0
prodigy_beta3: null
prodigy_decouple: true
prodigy_safeguard_warmup: true
prodigy_use_bias_correction: true
prompts_file: ../dataset/prompts_and_classes_obj.txt
proportional_parameters: false
repeats: 1
resolution: 1024
save_safetensors: true
save_steps: 200
scaling: 25
seed: 42
shuffle: true
snr_gamma: null
symlink_best_model: true
target_modules:
- to_q
- to_k
- to_v
- to_out.0
text_encoder_lr: 5.0e-05
train_batch_size: 1
train_text_encoder: false
unique_token: zjw
use_8bit_adam: false
use_captions: false
use_gradient_checkpointing: true
use_idwt: true
validation_prompt: null
validation_steps: 100
wavelet_family: db1
with_prior_preservation: false
